"""Add young adult chat tables

Revision ID: 5d8f427c05b3
Revises: b050ecd2bc54
Create Date: 2026-05-13 15:40:22.369390

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5d8f427c05b3'
down_revision: Union[str, Sequence[str], None] = 'b050ecd2bc54'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('young_adult_chat_sessions',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('title', sa.String(length=100), nullable=True),
    sa.Column('intent', sa.String(length=50), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_young_adult_user_active_sessions', 'young_adult_chat_sessions', ['user_id', 'is_deleted'], unique=False)
    op.create_index(op.f('ix_young_adult_chat_sessions_id'), 'young_adult_chat_sessions', ['id'], unique=False)
    op.create_index(op.f('ix_young_adult_chat_sessions_is_deleted'), 'young_adult_chat_sessions', ['is_deleted'], unique=False)
    op.create_index(op.f('ix_young_adult_chat_sessions_user_id'), 'young_adult_chat_sessions', ['user_id'], unique=False)
    op.create_table('young_adult_chat_messages',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('session_id', sa.String(length=36), nullable=False),
    sa.Column('role', sa.String(length=10), nullable=False),
    sa.Column('encrypted_content', sa.Text(), nullable=False),
    sa.Column('provider_used', sa.String(length=50), nullable=True),
    sa.Column('tokens_consumed', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['session_id'], ['young_adult_chat_sessions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_young_adult_chat_messages_id'), 'young_adult_chat_messages', ['id'], unique=False)
    op.create_index(op.f('ix_young_adult_chat_messages_session_id'), 'young_adult_chat_messages', ['session_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_young_adult_chat_messages_session_id'), table_name='young_adult_chat_messages')
    op.drop_index(op.f('ix_young_adult_chat_messages_id'), table_name='young_adult_chat_messages')
    op.drop_table('young_adult_chat_messages')
    op.drop_index(op.f('ix_young_adult_chat_sessions_user_id'), table_name='young_adult_chat_sessions')
    op.drop_index(op.f('ix_young_adult_chat_sessions_is_deleted'), table_name='young_adult_chat_sessions')
    op.drop_index(op.f('ix_young_adult_chat_sessions_id'), table_name='young_adult_chat_sessions')
    op.drop_index('idx_young_adult_user_active_sessions', table_name='young_adult_chat_sessions')
    op.drop_table('young_adult_chat_sessions')
    # ### end Alembic commands ###
