"""update_tos_ledger

Revision ID: 709844c4c19f
Revises: 83526656f5b4
Create Date: 2026-09-27 00:04:42.897864

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '709844c4c19f'
down_revision: Union[str, Sequence[str], None] = '83526656f5b4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tos_audit_ledger',
    sa.Column('request_id', sa.UUID(), nullable=False),
    sa.Column('client_name', sa.String(length=255), nullable=False),
    sa.Column('client_email', sa.String(length=255), nullable=False),
    sa.Column('is_parental_consent', sa.Boolean(), nullable=False),
    sa.Column('minor_name', sa.String(length=255), nullable=True),
    sa.Column('minor_age', sa.Integer(), nullable=True),
    sa.Column('ip_address', sa.String(length=45), nullable=False),
    sa.Column('sha512_hash', sa.String(length=128), nullable=False),
    sa.Column('storage_path', sa.String(length=512), nullable=False),
    sa.Column('execution_timestamp', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('(is_parental_consent = false AND minor_name IS NULL AND minor_age IS NULL) OR (is_parental_consent = true AND minor_name IS NOT NULL AND minor_age <= 17)', name='chk_parental_consent'),
    sa.PrimaryKeyConstraint('request_id')
    )
    op.create_index(op.f('ix_tos_audit_ledger_client_email'), 'tos_audit_ledger', ['client_email'], unique=False)
    op.create_index(op.f('ix_tos_audit_ledger_request_id'), 'tos_audit_ledger', ['request_id'], unique=False)
    op.create_index(op.f('ix_tos_audit_ledger_sha512_hash'), 'tos_audit_ledger', ['sha512_hash'], unique=True)
    op.drop_index(op.f('ix_document_signatures_client_email'), table_name='document_signatures')
    op.drop_index(op.f('ix_document_signatures_document_hash'), table_name='document_signatures')
    op.drop_index(op.f('ix_document_signatures_id'), table_name='document_signatures')
    op.drop_table('document_signatures')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('document_signatures',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('client_name', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('client_email', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('ip_address', sa.VARCHAR(length=45), autoincrement=False, nullable=False),
    sa.Column('document_hash', sa.VARCHAR(length=64), autoincrement=False, nullable=False),
    sa.Column('storage_path', sa.VARCHAR(length=512), autoincrement=False, nullable=False),
    sa.Column('signed_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('minor_name', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('minor_age', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('document_signatures_pkey'))
    )
    op.create_index(op.f('ix_document_signatures_id'), 'document_signatures', ['id'], unique=False)
    op.create_index(op.f('ix_document_signatures_document_hash'), 'document_signatures', ['document_hash'], unique=True)
    op.create_index(op.f('ix_document_signatures_client_email'), 'document_signatures', ['client_email'], unique=False)
    op.drop_index(op.f('ix_tos_audit_ledger_sha512_hash'), table_name='tos_audit_ledger')
    op.drop_index(op.f('ix_tos_audit_ledger_request_id'), table_name='tos_audit_ledger')
    op.drop_index(op.f('ix_tos_audit_ledger_client_email'), table_name='tos_audit_ledger')
    op.drop_table('tos_audit_ledger')
    # ### end Alembic commands ###
