"""create_kids_ai_buddy_and_sync_users

Revision ID: 72f67181dffc
Revises: c5448b96b7e2
Create Date: 2026-05-04 11:52:46.195859

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '72f67181dffc'
down_revision: Union[str, Sequence[str], None] = 'c5448b96b7e2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('kids_chat_sessions',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('title', sa.String(length=100), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_user_active_sessions', 'kids_chat_sessions', ['user_id', 'is_deleted'], unique=False)
    op.create_index(op.f('ix_kids_chat_sessions_id'), 'kids_chat_sessions', ['id'], unique=False)
    op.create_index(op.f('ix_kids_chat_sessions_is_deleted'), 'kids_chat_sessions', ['is_deleted'], unique=False)
    op.create_index(op.f('ix_kids_chat_sessions_user_id'), 'kids_chat_sessions', ['user_id'], unique=False)
    op.create_table('kids_chat_messages',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('session_id', sa.String(length=36), nullable=False),
    sa.Column('role', sa.String(length=10), nullable=False),
    sa.Column('encrypted_content', sa.Text(), nullable=False),
    sa.Column('provider_used', sa.String(length=50), nullable=True),
    sa.Column('tokens_consumed', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['session_id'], ['kids_chat_sessions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_kids_chat_messages_id'), 'kids_chat_messages', ['id'], unique=False)
    op.create_index(op.f('ix_kids_chat_messages_session_id'), 'kids_chat_messages', ['session_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_kids_chat_messages_session_id'), table_name='kids_chat_messages')
    op.drop_index(op.f('ix_kids_chat_messages_id'), table_name='kids_chat_messages')
    op.drop_table('kids_chat_messages')
    op.drop_index(op.f('ix_kids_chat_sessions_user_id'), table_name='kids_chat_sessions')
    op.drop_index(op.f('ix_kids_chat_sessions_is_deleted'), table_name='kids_chat_sessions')
    op.drop_index(op.f('ix_kids_chat_sessions_id'), table_name='kids_chat_sessions')
    op.drop_index('idx_user_active_sessions', table_name='kids_chat_sessions')
    op.drop_table('kids_chat_sessions')
    # ### end Alembic commands ###
