"""add minor guardianship fields

Revision ID: 83526656f5b4
Revises: a003dea26bae
Create Date: 2026-07-24 23:26:24.868950

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '83526656f5b4'
down_revision: Union[str, Sequence[str], None] = 'a003dea26bae'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('document_signatures', sa.Column('minor_name', sa.String(length=255), nullable=True))
    op.add_column('document_signatures', sa.Column('minor_age', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('document_signatures', 'minor_age')
    op.drop_column('document_signatures', 'minor_name')
    # ### end Alembic commands ###
