"""add_document_signatures_table

Revision ID: a003dea26bae
Revises: 5d8f427c05b3
Create Date: 2026-07-09 16:37:07.208570

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a003dea26bae'
down_revision: Union[str, Sequence[str], None] = '5d8f427c05b3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('document_signatures',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('client_name', sa.String(length=255), nullable=False),
    sa.Column('client_email', sa.String(length=255), nullable=False),
    sa.Column('ip_address', sa.String(length=45), nullable=False),
    sa.Column('document_hash', sa.String(length=64), nullable=False),
    sa.Column('storage_path', sa.String(length=512), nullable=False),
    sa.Column('signed_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_document_signatures_client_email'), 'document_signatures', ['client_email'], unique=False)
    op.create_index(op.f('ix_document_signatures_document_hash'), 'document_signatures', ['document_hash'], unique=True)
    op.create_index(op.f('ix_document_signatures_id'), 'document_signatures', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_document_signatures_id'), table_name='document_signatures')
    op.drop_index(op.f('ix_document_signatures_document_hash'), table_name='document_signatures')
    op.drop_index(op.f('ix_document_signatures_client_email'), table_name='document_signatures')
    op.drop_table('document_signatures')
    # ### end Alembic commands ###
