"""create_kids_video_tables

Revision ID: acf98d8c1bd2
Revises: 39cbb5dba282
Create Date: 2026-05-06 00:09:59.156376

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'acf98d8c1bd2'
down_revision: Union[str, Sequence[str], None] = '39cbb5dba282'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('kid_videos',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('topic', sa.String(length=100), nullable=False),
    sa.Column('duration', sa.String(length=10), nullable=False),
    sa.Column('thumbnail_url', sa.String(length=500), nullable=True),
    sa.Column('video_url', sa.String(length=500), nullable=False),
    sa.Column('transcript', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_kid_videos_title'), 'kid_videos', ['title'], unique=False)
    op.create_index(op.f('ix_kid_videos_topic'), 'kid_videos', ['topic'], unique=False)
    op.create_table('kid_video_progress',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('video_id', sa.String(length=36), nullable=False),
    sa.Column('watched_percentage', sa.Integer(), nullable=False),
    sa.Column('last_watched_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint('watched_percentage >= 0 AND watched_percentage <= 100', name='chk_kid_watched_percentage_range'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['video_id'], ['kid_videos.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'video_id', name='uix_kid_user_video_progress')
    )
    op.create_index('idx_kid_user_video', 'kid_video_progress', ['user_id', 'video_id'], unique=False)
    op.create_index(op.f('ix_kid_video_progress_user_id'), 'kid_video_progress', ['user_id'], unique=False)
    op.create_index(op.f('ix_kid_video_progress_video_id'), 'kid_video_progress', ['video_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_kid_video_progress_video_id'), table_name='kid_video_progress')
    op.drop_index(op.f('ix_kid_video_progress_user_id'), table_name='kid_video_progress')
    op.drop_index('idx_kid_user_video', table_name='kid_video_progress')
    op.drop_table('kid_video_progress')
    op.drop_index(op.f('ix_kid_videos_topic'), table_name='kid_videos')
    op.drop_index(op.f('ix_kid_videos_title'), table_name='kid_videos')
    op.drop_table('kid_videos')
    # ### end Alembic commands ###
