"""add teens heal ai models

Revision ID: b050ecd2bc54
Revises: e853578ab5dd
Create Date: 2026-05-08 22:56:16.770720

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'b050ecd2bc54'
down_revision: Union[str, Sequence[str], None] = 'e853578ab5dd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('teens_chat_sessions',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('title', sa.String(length=100), nullable=True),
    sa.Column('intent', sa.String(length=50), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_teens_user_active_sessions', 'teens_chat_sessions', ['user_id', 'is_deleted'], unique=False)
    op.create_index(op.f('ix_teens_chat_sessions_id'), 'teens_chat_sessions', ['id'], unique=False)
    op.create_index(op.f('ix_teens_chat_sessions_is_deleted'), 'teens_chat_sessions', ['is_deleted'], unique=False)
    op.create_index(op.f('ix_teens_chat_sessions_user_id'), 'teens_chat_sessions', ['user_id'], unique=False)
    op.create_table('teens_chat_messages',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('session_id', sa.String(length=36), nullable=False),
    sa.Column('role', sa.String(length=10), nullable=False),
    sa.Column('encrypted_content', sa.Text(), nullable=False),
    sa.Column('provider_used', sa.String(length=50), nullable=True),
    sa.Column('tokens_consumed', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['session_id'], ['teens_chat_sessions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_teens_chat_messages_id'), 'teens_chat_messages', ['id'], unique=False)
    op.create_index(op.f('ix_teens_chat_messages_session_id'), 'teens_chat_messages', ['session_id'], unique=False)
    op.drop_index(op.f('idx_kid_user_video'), table_name='kid_video_progress')
    op.drop_index(op.f('ix_kid_video_progress_user_id'), table_name='kid_video_progress')
    op.drop_index(op.f('ix_kid_video_progress_video_id'), table_name='kid_video_progress')
    op.drop_table('kid_video_progress')
    op.drop_index(op.f('ix_kid_videos_title'), table_name='kid_videos')
    op.drop_index(op.f('ix_kid_videos_topic'), table_name='kid_videos')
    op.drop_table('kid_videos')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('kid_videos',
    sa.Column('id', sa.VARCHAR(length=36), autoincrement=False, nullable=False),
    sa.Column('title', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('topic', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('duration', sa.VARCHAR(length=10), autoincrement=False, nullable=False),
    sa.Column('thumbnail_url', sa.VARCHAR(length=500), autoincrement=False, nullable=True),
    sa.Column('video_url', sa.VARCHAR(length=500), autoincrement=False, nullable=False),
    sa.Column('transcript', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('kid_videos_pkey'))
    )
    op.create_index(op.f('ix_kid_videos_topic'), 'kid_videos', ['topic'], unique=False)
    op.create_index(op.f('ix_kid_videos_title'), 'kid_videos', ['title'], unique=False)
    op.create_table('kid_video_progress',
    sa.Column('id', sa.VARCHAR(length=36), autoincrement=False, nullable=False),
    sa.Column('user_id', sa.VARCHAR(length=36), autoincrement=False, nullable=False),
    sa.Column('video_id', sa.VARCHAR(length=36), autoincrement=False, nullable=False),
    sa.Column('watched_percentage', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('last_watched_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.CheckConstraint('watched_percentage >= 0 AND watched_percentage <= 100', name=op.f('chk_kid_watched_percentage_range')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('kid_video_progress_user_id_fkey'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['video_id'], ['kid_videos.id'], name=op.f('kid_video_progress_video_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('kid_video_progress_pkey')),
    sa.UniqueConstraint('user_id', 'video_id', name=op.f('uix_kid_user_video_progress'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.create_index(op.f('ix_kid_video_progress_video_id'), 'kid_video_progress', ['video_id'], unique=False)
    op.create_index(op.f('ix_kid_video_progress_user_id'), 'kid_video_progress', ['user_id'], unique=False)
    op.create_index(op.f('idx_kid_user_video'), 'kid_video_progress', ['user_id', 'video_id'], unique=False)
    op.drop_index(op.f('ix_teens_chat_messages_session_id'), table_name='teens_chat_messages')
    op.drop_index(op.f('ix_teens_chat_messages_id'), table_name='teens_chat_messages')
    op.drop_table('teens_chat_messages')
    op.drop_index(op.f('ix_teens_chat_sessions_user_id'), table_name='teens_chat_sessions')
    op.drop_index(op.f('ix_teens_chat_sessions_is_deleted'), table_name='teens_chat_sessions')
    op.drop_index(op.f('ix_teens_chat_sessions_id'), table_name='teens_chat_sessions')
    op.drop_index('idx_teens_user_active_sessions', table_name='teens_chat_sessions')
    op.drop_table('teens_chat_sessions')
    # ### end Alembic commands ###
